packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  - 'packages/locales/*'
  - 'packages/rxeditor/*'
  - 'packages/fieldy/*'
  - 'packages/fieldy-minions/*'
  - 'packages/minions/*'
  - 'apps/*'
  - 'examples/*'
  - 'internal/vite-config'
  # exclude packages that are inside test directories
  - '!**/test/**'
